target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'sqlite3', '~> 3.42.0'
  pod 'shared', :path => '../shared'
end

# see https://github.com/cashapp/sqldelight/issues/1442#issuecomment-1627591933

# iosApp's podfile
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
        end
    end
end